language: python
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: isqpElDIqySBDZIhcVtNfQtXnCuxJ7BVR/rrj3OOKkBXIUTGu0Zbg4u2L7OKlSjbrtbRwRoSWK93R5wSvYygSrq2qJ/cRug24od4Sv5OA2dA/LzQU+UTOKTGc7PA9XvmE2PhOOcsEBMLUQGc4AvxQ9ZHIcdJc7CjcypOnSubxgkGH0C2oqVnCxRvKK5UFbFXzexC2nuzjdEjP4V/pv+9VkE/BZ4mJ7PJBV7tDaBklgu5sBi5YZWNayGv6v7GScwDhDJgIpIN4hRfiYaR6UYBQScWwQ3i1mc9Mthb2lmZpqdYROJt+QOnh2y2NuKT2RseW9F9jBIA8RuRByBK8lsZ538qOy8L4mGUlKCm8DhIKmTYPGK75taQK0bpU8P8PjZp+vRjytpGtWBhtqb3pD1HV8oR5daZ92EXscjJ/CVy54SCMPY9i5VMPXNLikXO33KdMfCNNYO5bgCEy/CtKNcCUcPGFll/KNh5V6OoBpAW2Kcr+0wWkY4llg109xVj0l0hi2cIJvApKl88SjYtTGK0DeHb380bBl1lTk1im8gZnMXMjGA+Cvcv55yByzE4eFgcgDaVzwYKN+JWkO1FmlrgICY+TvrRxLVC81JB0wFcqjXcYLUdmgfUXzvo7HjjLoK5qLe2hp+p/J5M0irKkGROxq8Q1VAkY9Z07BcuFtuyVCA=
  app: Moon_Jelly
  on:
    repo: nshamszadeh/Moon_Jelly
